language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
notifications:
  email: false
  irc:
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
    channels:
      secure: Al70IaBBA1mSDuFOKO3Lxoby0tnptH1FXswGG2D9tV7qjwNHvYRQrZgyB+6m0gETv2pGaQEtFod42Te6WiH0YfNDKS3GS7XxD9cQi5HY2IvPQbhlcViRYrD2v6iA2hSM3980tVgon/rduWl8AF2skLHiVbxZEm9Yq0TRIAo3bFo=
